---
title: "partial_pdf"
author: "me"
date: "11/30/2019"
output: pdf_document
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(webshot)
library(tidyverse)
library(socviz)
library(usmap)
library(cowplot)
library(maps)
library(mapproj)
library(RColorBrewer)
library(lubridate)
library(tinytex)
library(knitr)
library(htmltools)
library(leaflet)
webshot::install_phantomjs

```

```{r locations, message=FALSE, echo = FALSE}
sbuxloc <- read_csv("data/sbuxlocations.csv")
dnknloc <- read_csv("data/dnknlocations.csv", col_names = FALSE)

dnknloc <- dnknloc %>%
  rename(Longitude = X1,
         Latitude = X2,
         Specs = X3,
         Location = X4)
sbuxloc <- sbuxloc %>%
  filter(Country %in% c("US"))

dnknloc <- dnknloc %>%
  mutate(store = "Dunkin")
sbuxloc <- sbuxloc %>%
  mutate(store = "Starbucks")

dnknloc <- dnknloc %>%
  separate(Specs, c("Specs", "State"), sep = ",")

dnknloc <- dnknloc %>%
  mutate(State = dnknloc %>%
           pull(State) %>%
           str_replace_all("\\ ", ""))

dnknLabel <- sprintf("<b>Dunkin'</b><br>%s", dnknloc$State) %>%
  lapply(htmltools::HTML)
sbuxLabel <- sprintf("<b>Starbucks</b><br>%s", sbuxloc$`State/Province`) %>%
  lapply(htmltools::HTML)
```
Dunkin' Leaflet
```{r leaflet_maps_dnkn, message = FALSE}
dnknloc %>%
  leaflet(width = "100%", options = leafletOptions(zoomSnap = 0.1)) %>%
  setView(lng = -100, lat = 40, zoom = 3) %>%
  addTiles() %>%
  addMarkers(~Longitude, ~Latitude, popup = dnknLabel, label = dnknLabel)
```
Starbucks Leaflet
```{r leaflet_maps_sbux, message = FALSE}
sbuxloc %>%
  leaflet(width = "100%", options = leafletOptions(zoomSnap = 0.1)) %>%
  setView(lng = -100, lat = 40, zoom = 3) %>%
  addTiles() %>%
  addMarkers(~Longitude, ~Latitude, popup = sbuxLabel, label = sbuxLabel)
```

```{r dnkn_sbux, message = FALSE, echo = FALSE}
dnkn_sbux <- tibble(
  longitude = c(dnknloc %>%
                  pull(Longitude), sbuxloc %>%
                  pull(Longitude)),
  latitude = c(dnknloc %>%
                 pull(Latitude), sbuxloc %>%
                 pull(Latitude)),
  store = c(dnknloc %>%
              pull(store), sbuxloc %>%
              pull(store)),
  state = c(dnknloc %>%
              pull(State), sbuxloc %>%
              pull(`State/Province`))
)

scale_coord <- function(abbreviation, x, y) {
  library(usmap)
  values <- tibble(
    abbreviation = abbreviation,
    x = x,
    y = y
  )
  usMap <- us_map(regions = "states")
  scaler <- usMap %>%
    group_by(abbr) %>%
    summarize(max.x = max(x),
              max.y = max(y),
              min.x = min(x),
              min.y = min(y))
  scaler <- scaler %>%
    mutate(variation.x = max.x - min.x,
           variation.y = max.y - min.y)
  base <- values %>%
    group_by(abbreviation) %>%
    summarize(max.x = max(x),
              max.y = max(y),
              min.x = min(x),
              min.y = min(y))
  base <- base %>%
    mutate(variation.x = max.x - min.x,
           variation.y = max.y - min.y)
  longitude <- c()
  latitude <- c()
  indexes <- c()
  count <- 1
  for(state in values$abbreviation) {
    for(abbrs in scaler$abbr) {
      if(state == abbrs) {
        indexes <- c(indexes, count)
      }
      count <- count + 1
    }
    count <- 1
  }
  count <- 1
  for(index in indexes) {
    longitude <- c(longitude, ((values$x[count]-base$min.x[index])/base$variation.x[index]) * scaler$variation.x[index] + scaler$min.x[index])
    latitude <- c(latitude, ((values$y[count]-base$min.y[index])/base$variation.y[index]) * scaler$variation.y[index] + scaler$min.y[index])
    count <- count + 1
  }
  return_tibble <- tibble(
    state = values$abbreviation,
    long = longitude,
    lat = latitude
  )
  return(return_tibble)
}

modified_values <- scale_coord(dnkn_sbux$state, dnkn_sbux$longitude, dnkn_sbux$latitude) %>%
  mutate(Store = dnkn_sbux$store)
```
Locations Graphs
```{r graph_locations, message = FALSE}
ggplot() +
  geom_polygon(data = us_map(regions = "states"), mapping = aes(x = x, y = y, group = group), color = "gray", fill = "cornsilk") +
  geom_point(data = modified_values, mapping = aes(x = long, y = lat, color = Store), alpha = 0.1) +
  coord_equal() +
  theme_map() +
  scale_color_manual(values = c("blue", "orange")) +
  labs(title = "Restuarant Locations in the US",
       subtitle = "Dunkin' vs Starbucks") +
  guides(color = guide_legend(title = "Brand")) +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))

```

```{r store_per_state_starbucks, message = FALSE, echo = FALSE} 
#gather data from csv files
starbuck_local<- read_csv("data/directory.csv")
starbuck_zip<-read_csv("data/ZIP-COUNTY-FIPS-2018.csv")

#getting states dataset
us_states<-map_data("state")

#chaging dataset zip to numeric
starbuck_zip<-starbuck_zip %>% 
  mutate(ZIP=as.numeric(ZIP)) %>% 
  distinct(CITY, .keep_all = TRUE)

#filtering by country and renaming
starbuck_local <- starbuck_local %>% 
  filter(Country == "US") %>% 
  rename(
    CITY = City,
    STATE = `State/Province`
  )

#joining datasets by city
data<-left_join(starbuck_local,starbuck_zip,by=c("CITY","STATE"))

#grouping by state and removing na values
data<- data %>% 
  group_by(STATE) %>% 
  count() %>%
  na.omit() 

#renaming states to match join function
us_states<-us_map("states") %>% 
  rename(STATE=abbr)

#left joining and renaming variables
data<-left_join(us_states,data,by='STATE') %>% 
  rename(count = n)

temp_data <- data %>% 
  select(STATE, count) %>% 
  group_by(STATE) %>% 
  summarise(count = mean(count))

coord <- us_states %>% 
  select(x, y, STATE) %>% 
  group_by(STATE) %>% 
  summarise(
    x_avg = mean(x),
    y_avg = mean(y))

new_data <- merge(temp_data, coord, by = "STATE" )

final_data <- merge(new_data, us_states, by = "STATE" )

#plot data for locations
centroid <- aggregate(data=final_data, cbind(x_avg, y_avg) ~ count + group, FUN=mean) 
data %>% 
  ggplot() +
  geom_polygon(mapping = aes(x=x,y=y,group=group,fill=count), color = "lightgray", size = 0.5) +
  coord_equal()+
  theme_map()+
  theme(panel.background = element_blank()) + ggtitle("US Starbuck's Location", subtitle = "Average # of Stores") + labs(fill = "Count")+
  theme(legend.position="bottom", plot.title = element_text(hjust = 0.5),plot.subtitle =  element_text(hjust = 0.5)) +geom_text(data = centroid, mapping = aes(x_avg,y_avg, group = group, label = count), color = "black", inherit.aes = FALSE)+ scale_fill_gradient(low = "orange", high = "purple", guide = guide_legend())

```

```{r density, message=FALSE, echo = FALSE}
sq_mileage <- read_csv("data/mileage.csv")
DNKN_loc <- read_csv("data/DunkinAvgLocations#2.csv")
SBUX_loc <- read_csv("data/StarbuckAvgLocations#2.csv") %>%
  rename(n = count)

DNKN_loc <- DNKN_loc %>%
  distinct(STATE, n) %>%
  rename(state = STATE)
SBUX_loc <- SBUX_loc %>%
  distinct(STATE, n) %>%
  rename(state = STATE)

DNKN_loc <- left_join(us_map(region = "states") %>%
                        rename(state = abbr), DNKN_loc, by = "state")
SBUX_loc <- left_join(us_map(region = "states") %>%
                        rename(state = abbr), SBUX_loc, by = "state")

sq_mileage <- sq_mileage %>%
  rename(full = state,
         state_area = mileage)

DNKN_loc <- left_join(DNKN_loc, sq_mileage, by = "full")
SBUX_loc <- left_join(SBUX_loc, sq_mileage, by = "full")

DNKN_loc <- DNKN_loc %>%
  mutate(density = n/state_area)
SBUX_loc <- SBUX_loc %>%
  mutate(density = n/state_area)
```
Density with DC
```{r DC_graphs, message = FALSE}
DNKN_loc %>%
  ggplot(mapping = aes(x = x, y = y, group = group, fill = density)) +
  geom_polygon() +
  coord_equal() +
  theme_map() +
  scale_fill_distiller(palette = "Set1") +
  labs(title = "Dunkin' Locations") +
  theme(plot.title = element_text(hjust = 0.5))
SBUX_loc %>%
  ggplot(mapping = aes(x = x, y = y, group = group, fill = density)) +
  geom_polygon() +
  coord_equal() +
  theme_map() +
  scale_fill_distiller(palette = "Set1") +
  labs(title = "Starbucks Locations") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r filter_DC, message = FALSE, echo = FALSE}
DNKN_loc <- DNKN_loc %>%
  filter(state %nin% c("DC"))
SBUX_loc <- SBUX_loc %>%
  filter(state %nin% c("DC"))
```
Density without DC
```{r dens_graphs, message = FALSE}
DNKN_loc %>%
  ggplot(mapping = aes(x = x, y = y, group = group, fill = density)) +
  geom_polygon() +
  coord_equal() +
  theme_map() +
  scale_fill_distiller(palette = "Set1") +
  labs(title = "Dunkin' Locations") +
  theme(plot.title = element_text(hjust = 0.5))
SBUX_loc %>%
  ggplot(mapping = aes(x = x, y = y, group = group, fill = density)) +
  geom_polygon() +
  coord_equal() +
  theme_map() +
  scale_fill_distiller(palette = "Set1") +
  labs(title = "Starbucks Locations") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r stock, message = FALSE, echo = FALSE}

DNKN <- read_csv("data/modified_DNKN.csv")
SBUX <- read_csv("data/modified_SBUX.csv")

DNKN <- DNKN %>%
  mutate(stock = "DNKN")
SBUX <- SBUX %>%
  mutate(stock = "SBUX")

D_S <- tibble(
  timestamp = c(DNKN %>%
                  pull(timestamp),
                SBUX %>%
                  pull(timestamp)),
  stock = c(DNKN %>%
              pull(stock),
            SBUX %>%
              pull(stock)),
  close = c(DNKN %>%
              pull(close),
            SBUX %>%
              pull(close))
)
```
Monthly Stock Close
```{r monthly_stock, message = FALSE}
D_S %>%
  group_by(stock) %>%
  ggplot() +
  geom_line(mapping = aes(x = timestamp, y = close, color = stock)) +
  scale_color_manual(values = c("red", "green")) +
  labs(title = "Monthly Close Values",
       x = "Year",
       y = "Close Value") +
  guides(color = guide_legend(title = "Stock Symbols")) +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r mutate_DS, message = FALSE, echo = FALSE}
yrly <- D_S %>%
  mutate(year = year(timestamp)) %>%
  group_by(year, stock) %>%
  summarize(mean_close = mean(close))
```
Yearly Mean Stock Close
```{r yearly_mean, message = FALSE}
yrly %>%
  group_by(stock) %>%
  ggplot() +
  geom_line(mapping = aes(x = year, y = mean_close, color = stock)) +
  scale_color_manual(values = c("red", "green")) +
  labs(title = "Average Monthly Close Value by Year",
       x = "Year",
       y = "Mean Close Value") +
  guides(color = guide_legend(title = "Stock Symbols")) +
  theme(plot.title = element_text(hjust = 0.5))

```

```{r growth, message = FALSE, echo = FALSE}
growth_dnkn <- D_S %>%
  arrange(desc(timestamp)) %>%
  group_by(stock) %>%
  filter(stock %in% c("DNKN"))
growth_sbux <- D_S %>%
  arrange(desc(timestamp)) %>%
  group_by(stock) %>%
  filter(stock %in% c("SBUX"))
count <- 0
g_d <- c()
g_s <- c()
for(x in growth_dnkn$close) {
  if(count != 0) {
    g_d <- c(g_d, x - growth_dnkn$close[count])
  } else {
    g_d <- c(g_d, 50000)
  }
  count <- count + 1
}
count <- 0
for(x in growth_sbux$close) {
  if(count != 0) {
    g_s <- c(g_s, x - growth_dnkn$close[count])
  } else {
    g_s <- c(g_s, 50000)
  }
  count <- count + 1
}
growth_dnkn <- growth_dnkn %>%
  mutate(change = g_d)
growth_sbux <- growth_sbux %>%
  mutate(change = g_s)

growth <- tibble(
  timestamp = c(growth_dnkn$timestamp, growth_sbux$timestamp),
  stock = c(growth_dnkn$stock, growth_sbux$stock),
  change = c(growth_dnkn$change, growth_sbux$change)
)

growth <- growth %>%
  filter(change %nin% c(50000))
```
Growth Plots
```{r growth_plot, message = FALSE}
growth %>%
  group_by(stock) %>%
  ggplot() +
  geom_line(mapping = aes(x = timestamp, y = change, color = stock)) +
  scale_color_manual(values = c("red", "green")) +
  labs(title = "Growth of Stocks",
       x = "Year",
       y = "Change") +
  guides(color = guide_legend(title = "Stock Symbols")) +
  theme(plot.title = element_text(hjust = 0.5))
  
```

```{r revenue_starbucks, message = FALSE, echo = FALSE, warning = FALSE}
#Revenue of company stores
starbuck_rev<- read_csv("data/starbucks.csv")

starbuck_rev <- starbuck_rev %>% 
  select(year, Company_Operated_Stores:Total_OS)

starbuck_rev <- starbuck_rev %>% 
  select(Company_Operated_Stores, License_Stores, Other, Total,year) %>% 
  gather(Type, count, Company_Operated_Stores, License_Stores, Other, Total) %>% 
  na.omit()

starbuck_rev <- starbuck_rev %>% 
  group_by(Type, year) %>% 
  summarise(mean = mean(count))
# starbuck_rev %>% 
#   ggplot() + 
#   geom_col(mapping = aes(reorder(year, mean),
#                          y = mean, fill=Type)) + labs(title = "Starbuck's Revenue")+
#   theme(plot.title = element_text(hjust = 0.5)) + xlab("Year") + ylab("Revenue")  +  facet_wrap(~Type, nrow = 3, scales = "free") + coord_flip()

starbuck_rev %>%
group_by(Type) %>%
  ggplot(mapping = aes(x = year, y = mean)) +
  geom_line(mapping = aes(color = Type)) + ylab("Revenue") + xlab("Year")+ facet_wrap(~Type, nrow = 3,scales = "free") + labs(title = "Starbuck's Revenue")+ theme(plot.title = element_text(hjust = 0.5))

write_csv(starbuck_rev, "data/TotalRevenue.csv")

#revenue by country
starbuck_rev<- read_csv("data/starbucks.csv")

starbuck_rev <- starbuck_rev %>% 
  select(year, Company_Operated_Stores:Total_OS)

starbuck_rev <- starbuck_rev %>% 
  select(Americas_Licensed, EMEA_Licensed, CP_Licensed, Total_LS, year) %>% 
  gather(Type, count, Americas_Licensed, EMEA_Licensed, CP_Licensed, Total_LS) %>% 
  na.omit()

starbuck_rev <- starbuck_rev %>% 
  group_by(Type, year) %>% 
  summarise(mean = mean(count))
# starbuck_rev %>% 
#   ggplot() + 
#   geom_col(mapping = aes(reorder(year, mean),
#                          y = mean, fill=Type)) + labs(title = "Starbuck's Revenue/Country(LS)")+
#   theme(plot.title = element_text(hjust = 0.5)) + xlab("Year") + ylab("Revenue") + scale_fill_brewer(palette = "Set2")  +  facet_wrap(~Type, nrow = 3, scales = "free") + coord_flip()
#   scale_y_continuous(limits = c(0, 20000))

starbuck_rev %>%
  group_by(Type) %>%
  ggplot(mapping = aes(x = year, y = mean)) +
  geom_line(mapping = aes(color = Type)) + ylab("Revenue") + xlab("Year")+ facet_wrap(~Type, nrow = 3,scales = "free")+ labs(title = "Starbuck's Revenue")+ labs(title = "Starbuck's Revenue/Country(LS)")+
theme(plot.title = element_text(hjust = 0.5))


write_csv(starbuck_rev, "data/revenue(Ls).csv")
#revenue by country(com)

starbuck_rev<- read_csv("data/starbucks.csv")

starbuck_rev <- starbuck_rev %>% 
  select(year, Company_Operated_Stores:Total_OS)

starbuck_rev <- starbuck_rev %>% 
  select(Americas_Com, EMEA_Com, CP_Com, Total_OS, year) %>% 
  gather(Type, count, Americas_Com, EMEA_Com, CP_Com, Total_OS) %>% 
  na.omit()

starbuck_rev <- starbuck_rev %>% 
  group_by(Type, year) %>% 
  summarise(mean = mean(count))

# starbuck_rev %>% 
#   ggplot() + 
#   geom_col(mapping = aes(reorder(year, mean),
#                          y = mean, fill=Type)) + labs(title = "Starbuck's Reveue/Country(OS)")+
#   theme(plot.title = element_text(hjust = 0.5)) + xlab("Year") + ylab("Revenue") + scale_fill_brewer(palette = "Set2")  +  facet_wrap(~Type, nrow = 3, scales = "free") + coord_flip()

starbuck_rev %>%
  group_by(Type) %>%
  ggplot(mapping = aes(x = year, y = mean, )) +
  geom_line(mapping = aes(color = Type)) + ylab("Revenue") + xlab("Year")+ facet_wrap(~Type, nrow = 3,scales = "free") + labs(title = "Starbuck's Reveue/Country(OS)") + theme(plot.title = element_text(hjust = 0.5))

```